demo0:
	gcc demo0.c -o demo0.o
	gcc -g -o gdb_demo0 demo0.c

demo1:
	gcc demo1.c -o demo1.o
	gcc -g -o gdb_demo1 demo1.c

demo2:
	gcc demo2.c -o demo2.o
	gcc -g -o gdb_demo2 demo2.c

clean:
	@rm *.o
	@rm gdb_*
