demo0:
	gcc demo0.c -o demo0.o
	gcc -g -o gdb_demo0 demo0.c

demo1:
	gcc demo1.c -o demo1.o
	gcc -g -o gdb_demo1 demo1.c

demo2:
	gcc demo2.c -o demo2.o
	gcc -g -o gdb_demo2 demo2.c

demo3:
	gcc demo3.c -o demo3.o
	gcc -g -o gdb_demo3 demo3.c

demo4:
	gcc demo4.c -o demo4.o
	gcc -g -o gdb_demo4 demo4.c

demo5:
	gcc demo5.c -rdynamic -o demo5.o
	gcc -g -o gdb_demo5 demo5.c

clean:
	@rm *.o
	@rm gdb_*
